Created all the Functions
itsnestee/PFMCPP_Project2 pull request #1
Opened 2021-07-14 20:53 UTC by itsnestee

Added ten functions.

2021-07-16 17:22 UTC, matkatmusic requested changes
The indentation for all of your functions is incorrect.
please read the Readme.MD, look for the section explaining the Course Coding Standard and conform to the Course Coding Standard.
- [x] revise

2021-07-16 17:22 UTC, matkatmusic commented on main.cpp
> +    char grade = 'C';
```
2) for each primitive type, write out 3 variable declarations
```
- [ ] revise

2021-07-16 17:22 UTC, matkatmusic commented on main.cpp
> +    ignoreUnused(grade);
```
    b) at the end of the function, call ignoreUnused ONCE and pass ALL of your variables to it.
```
- [ ] revise

2021-07-16 17:22 UTC, matkatmusic commented on main.cpp
> +    ignoreUnused(masteringCPlusPlus);
```
        c) pass the local variables to ignoreUnused() as you did in 2b)
```
as a reminder of what 2b) said:
```
    call ignoreUnused ONCE and pass ALL of your variables to it.
```
- [ ] revise

2021-07-18 15:51 UTC, itsnestee commented on main.cpp
> +    char grade = 'C';
Ok, example. 
as I have int siblings = 4; I should do something like;
siblings = 5;
siblings = 7;
siblings = 15;  is this what you mean by creating 3 variable declarations?

2021-07-18 21:41 UTC, matkatmusic requested changes
This is a list of all the things I need you to fix in this project.
- Do NOT initialize boolean variables with `0` or `1`.  use `true` or `false`
- fix your indentation.  Set up Replit to use 4 spaces when you press the 'tab' key.
- do not put spaces around `(` or `)` 
- do not add extra blank lines inside your functions unless they improve readability.
- write `return {};` not `return{};`.  it's easier to read.
- [ ] revise

2021-07-18 21:41 UTC, matkatmusic commented on main.cpp
> +         grade = 'D';
This is not declaring 3 variables of a particular type. and assigning them an initial value.
This is declaring 1 variable of a particular type and changing its value 4 times.

The purpose of this assignment is to teach you how to declare variables and initialize them with values.
Also, do not initialize boolean variables with `0` or `1`.   Be explicit when you initialize booleans and use `true` or `false`.
- [ ] revise

2021-07-18 21:43 UTC, itsnestee commented on main.cpp
> +         grade = 'D';
Can you kindly show me an example?

2021-07-19 19:09 UTC, matkatmusic approved these changes

2021-07-19 19:09 UTC, merged